In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [3]:
#Диагональная, ортогональная, но не единичная(!)
a = np.array([[-1, 0],[0, 1]])
a @ a.T

array([[1, 0],
       [0, 1]])

In [6]:
#Верхнетреугольная, ортогональная
b = np.array([[1, 0],[0, -1]])
print(b)

[[ 1  0]
 [ 0 -1]]


In [7]:
# нижнетреугольная, ортогональная
c = np.array([[1, 0],[0, -1]])
print(c)

[[ 1  0]
 [ 0 -1]]


In [9]:
#Матрица, у которой определитель = 1, и все элементы не равны 0
b = np.array([[3, 2],
              [7, 5]])
dd = np.linalg.det(b)
print(b)
print(round(dd))

[[3 2]
 [7 5]]
1
