In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [3]:
#Диагональная, ортогональная, но не единичная(!)
a = np.array([[-1, 0],[0, 1]])
a @ a.T

array([[1, 0],
       [0, 1]])

In [6]:
#Верхнетреугольная, ортогональная
b = np.array([[1, 0],[0, -1]])
print(b)

[[ 1  0]
 [ 0 -1]]


In [7]:
# нижнетреугольная, ортогональная
c = np.array([[1, 0],[0, -1]])
print(c)

[[ 1  0]
 [ 0 -1]]


In [11]:
#Матрица, у которой определитель = 1, и все элементы не равны 0
b = np.array([[5, 7],
              [2, 3]])
dd = np.linalg.det(b)
print(b)
print(round(dd)) #15-14=1

[[5 7]
 [2 3]]
1


In [10]:
#Найдите собственные значения и собственные вектора матриц:

m = np.array([[2, 2],
              [1, 3]])
print(m)

[[2 2]
 [1 3]]


In [12]:
w,v = np.linalg.eig(m)

In [13]:
# Собственные числа матрицы m
w

array([1., 4.])

In [14]:
# Собственные векторы матрицы m
v

array([[-0.89442719, -0.70710678],
       [ 0.4472136 , -0.70710678]])