In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
A = np.arange(1, 10).reshape(3, 3)
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
B = np.eye(3)
print(B)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [4]:
C = A + B
print(C)

[[ 2.  2.  3.]
 [ 4.  6.  6.]
 [ 7.  8. 10.]]


In [5]:
v = np.array([1, 2, 3])

In [6]:
D = C @ v
print(D)

[15. 34. 53.]


In [7]:
C_1 = np.linalg.inv(C)
print(C_1)

[[-6.00000000e+00 -2.00000000e+00  3.00000000e+00]
 [-1.00000000e+00  5.00000000e-01  2.22044605e-17]
 [ 5.00000000e+00  1.00000000e+00 -2.00000000e+00]]
